### ISSUE TITLE
Remove 405 code in the yaml & test definition

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/OTPValidation#79]
**Problem description**
Following issue discussed [here](https://github.com/camaraproject/Commonalities/issues/285) in commonalities, the code 405 must not be described in the yaml and probably not either in the test definition.

**Expected behavior**
Remove 405 in the yaml & test scenario

**Alternative solution**

**Additional context**
@hdamker @tanjadegroot from a release management perspective, if we update the yaml we should shift the version to `1.0.0-rc.2` - correct?

**Comment by hdamker** [comment]
> @hdamker @tanjadegroot from a release management perspective, if we update the yaml we should shift the version to `1.0.0-rc.2` - correct?

See my comment https://github.com/camaraproject/DeviceStatus/issues/197#issuecomment-2296807310
